### ISSUE TITLE
Integrate with Google OIDC login

### ISSUE THREAD

**Issue by pjeziorowski** [appwish/web-ui#6]
Integrate with Google OIDC. Requirements:

1. Button 'Sign in with Google' somewhere in the UI - visual part doesn't matter - in this task we only care about the logic/integration with Google OIDC
2. Clicking button should start login with Google flow.
3. At the end of this process, we should have users ID Token accessible in the UI application.

Resources:
- post I wrote about OIDC in SPAs - https://dev.to/pjeziorowski/openid-connect-spa-backend-api-authentication-in-modern-webapps-1cd7
- Google documentation - https://developers.google.com/identity/protocols/OpenIDConnect

**Comment by gauravumrani** [comment]
@Parables are you working on this?

**Comment by pjeziorowski** [comment]
@gauravumrani I think you can take this, @Parables is helping me with a different task at the moment so I guess he's not working on this one, right @Parables?

**Comment by gauravumrani** [comment]
Okay, I will work on it.

**Comment by Parables** [comment]
@gauravumrani Yeah, go for this one... I wanna give React a second attempt so I will be doing the frontend stuff

**Comment by Parables** [comment]
Do we use Google only?

I wanna give  [NextAuth](https://github.com/iaincollins/next-auth) a try. What do you say?

**Comment by pjeziorowski** [comment]
For now just one provider (google) is enough but we'll add more for sure. You can give NextAuth a try @Parables.

**Comment by pjeziorowski** [comment]
Merged to master.
